// @ts-check
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettierRecommended from 'eslint-plugin-prettier/recommended';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'coverage/**',
      'node_modules/**',
      'eslint.config.mjs',
      // Generated by `prisma generate`; ships with its own eslint-disable header.
      'src/shared/infrastructure/prisma/generated/**',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  prettierRecommended,
  {
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.jest,
      },
      parserOptions: {
        projectService: {
          // Jest configs are plain CommonJS and live outside any tsconfig.
          allowDefaultProject: ['jest.config.js', 'test/jest-e2e.config.js'],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/explicit-member-accessibility': ['error', { accessibility: 'no-public' }],
      '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports' }],
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-unsafe-argument': 'error',
    },
  },
  /**
   * ARCHITECTURAL RULE: no file outside `infrastructure/` may import
   * `@prisma/client`, directly or indirectly. Enforced by the linter so a
   * violation breaks CI instead of relying on review.
   */
  {
    files: ['src/**/*.ts', 'test/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                '@prisma/client',
                '@prisma/client/**',
                '.prisma/**',
                // Prisma 7 emits the client into the project tree; reaching it by
                // relative path from outside `infrastructure/` is the same violation.
                '**/prisma/generated',
                '**/prisma/generated/**',
              ],
              message:
                'Prisma may only be imported from within an `infrastructure/` folder. Declare a port in `domain/` and implement it in `infrastructure/`.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/**/infrastructure/**/*.ts'],
    rules: {
      'no-restricted-imports': 'off',
    },
  },
  {
    files: ['**/*.spec.ts', '**/*.e2e-spec.ts'],
    rules: {
      '@typescript-eslint/unbound-method': 'off',
    },
  },
);
